server:
  port: 7000

spring:
  mvc:
    servlet:
      load-on-startup: 1
  application:
    name: zuul-server #此实例注册到eureka服务端的name

eureka:
  client:
    serviceUrl:
      #eureka服务端提供的注册地址 参考服务端配置的这个路径
      defaultZone: http://eureka:3000/eureka,http://eureka1:3001/eureka,http://eureka2:3002/eureka
  instance:
    instance-id: zuul-1 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseRenewalIntervalInSeconds: 10
    #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    leaseExpirationDurationInSeconds: 30

zuul:
  ignoredServices: '*' #禁用直接通过微服务名称进行调用
  prefix: /api
  strip-prefix: true
  routes:
    ignored-services: consume-goods
    goods: #自己定义的名称  商品服务
      serviceId: consume-goods
      path: /goods/**   #/* 是一级   /** 是多级
    order: #订单服务
      serviceId: provide-order
      path: /order/**
    user: #用户服务
      serviceId: provide-user
      path: /user/**






